# Generated by Django 2.2.11 on 2020-03-31 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('white', models.BooleanField(default=False)),
                ('grey', models.BooleanField(default=False)),
                ('black', models.BooleanField(default=False)),
                ('brown', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wood', models.BooleanField(default=False)),
                ('stone', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kitchen', models.BooleanField(default=False)),
                ('countertop', models.BooleanField(default=False)),
                ('tv', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Color')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Material')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Object')),
            ],
        ),
    ]
