# Generated by Django 2.2.11 on 2020-03-31 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pic',
            name='image',
            field=models.ImageField(default='.\\static\x07pp\\imagesY8967_1.jpg', upload_to=''),
        ),
    ]
