# Generated by Django 2.2.11 on 2020-04-02 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200402_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='pic',
            name='classify',
            field=models.ManyToManyField(to='app.Classify'),
        ),
    ]
