# Generated by Django 2.2.11 on 2020-04-03 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200403_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='pic',
            name='is_on_home_page_gallery',
            field=models.BooleanField(default=False),
        ),
    ]
