# Generated by Django 2.2.11 on 2020-04-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_pic_is_on_home_page_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pic',
            name='classify',
            field=models.ManyToManyField(blank=True, to='app.Classify'),
        ),
        migrations.AlterField(
            model_name='pic',
            name='color',
            field=models.ManyToManyField(blank=True, to='app.Color'),
        ),
        migrations.AlterField(
            model_name='pic',
            name='material',
            field=models.ManyToManyField(blank=True, to='app.Material'),
        ),
    ]
